const domManager = {
    findDom: function(){
        const addCategoryButton = document.querySelector(".add-cat");

        addCategoryButton.addEventListener("click", this.categoryPopup)
    },
    bindAttributes: function (target, pointer){
        Object.keys(pointer).forEach(attr => {
            target.setAttribute(attr, pointer[attr]);
        })
    },
    attributes: {
        catTitle: {
            name: 'cat-title',
            type: 'text',
            id: 'cat-title',
            required: '',
        },
        catTitleLabel: {
            for: 'cat-title'
        },
        catDescription: {
            name: 'cat-description',
            type: 'text',
            id: 'cat-description',
            required: '',
            maxlength: '45'
        },
        catDescriptionLabel: {
            for: 'cat-description'
        }
    },
    categoryPopup: function(){
        const modalSpace = document.querySelector(".modal-space");
        const popup = document.createElement("dialog");
        const form = document.createElement("form");
        const formDescription = document.createElement("p");
        const catTitleContainer = document.createElement("div")
        const catTitleLabel = document.createElement('label');
        const catTitle = document.createElement('input')
        const catDescriptionContainer = document.createElement("div");
        const catDescriptionLabel = document.createElement("label");
        const catDescription = document.createElement("textarea");
        //The way to prevent multiple modals from being created
        modalSpace.innerHTML = ''

        modalSpace.appendChild(popup)
        popup.appendChild(form);
        form.appendChild(formDescription);
        form.appendChild(catTitleContainer);
        catTitleContainer.appendChild(catTitleLabel);
        catTitleContainer.appendChild(catTitle);
        form.appendChild(catDescriptionContainer);
        catDescriptionContainer.appendChild(catDescriptionLabel)
        catDescriptionContainer.appendChild(catDescription);

        domManager.bindAttributes(catTitle, domManager.attributes.catTitle);

        domManager.bindAttributes(catDescription, domManager.attributes.catDescription);

        domManager.bindAttributes(catDescriptionLabel, domManager.attributes.catDescriptionLabel)

        domManager.bindAttributes(catTitleLabel, domManager.attributes.catTitleLabel)
        
        formDescription.textContent = "Please fill in the categories and text"
        catTitleLabel.textContent = "Enter the Category title:"
        catDescriptionLabel.textContent = "Please describe the Task Category:"

        formDescription.setAttribute('for', 'cat-title');

        popup.showModal();

        //add modal elems here and make it appended to the sidebar but visible in the middle. The form should be generated by code.

        //add the modal x to close button
        //the submit button
        //the catDescription... do we go for text area? lol idk - also how do we limit the amt of chars?
    }
};

export { domManager };