const domManager = {
    findDom: function(){
        const addCategoryButton = document.querySelector(".add-cat");

        addCategoryButton.addEventListener("click", this.categoryPopup)
    },
    categoryPopup: function(){
        const sidebarOptions = document.querySelector(".sidebar-options");
        const popup = document.createElement("dialog");
        const form = document.createElement("form");
        const formDescription = document.createElement("p");
        const catTitleContainer = document.createElement("div")
        const catTitleLabel = document.createElement('label');
        const catTitle = document.createElement('input')
        //find a way to prevent multiple modals from being created

        sidebarOptions.appendChild(popup)
        popup.appendChild(form);
        form.appendChild(formDescription);
        form.appendChild(catTitleContainer);
        catTitleContainer.appendChild(catTitleLabel);
        catTitleContainer.appendChild(catTitle);

        formDescription.textContent = "Please fill in the categories and text"
        catTitleLabel.textContent = "Enter the Category title:"

        formDescription.setAttribute('for', 'cat-title');
        catTitle.setAttribute('type', 'text');
        catTitle.setAttribute('name', 'cat-title')
        catTitle.setAttribute('id', 'cat-title');
        catTitle.setAttribute('required', '')
        popup.showModal();
        //add modal elems here and make it appended to the sidebar but visible in the middle. The form should be generated by code.
    }
};

export { domManager };